version: "3.8"
services:
  db:
    build:
      context: ./project/database
      dockerfile: Dockerfile
    container_name: "mysql"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./project/database/my.cnf:/etc/mysql/conf.d/my.cnf
    platform: linux/amd64
    ports:
      - "3306:3306"

  web:
    build:
      context: ./project/server
      dockerfile: Dockerfile
    container_name: "fastapi-server"
    volumes:
      - ./project/server:/usr/src/server
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql_data: