version: "3.8"
services:
  db:
    build:
      context: ./project/database
      dockerfile: Dockerfile
    container_name: "mysql"
    restart: always
    volumes:
      - ./project/database:/var/lib/mysql
      - ./project/database/my.cnf:/etc/mysql/conf.d/my.cnf
    platform: linux/amd64
    ports:
      - "3306:3306"
